{{- if eq (.Values.expose.type) "Route" }}
  {{- if .Capabilities.APIVersions.Has "route.openshift.io/v1/Route" }}
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ include "infinispan-helm-charts.name" . }}
  labels:
    app: infinispan-route
  {{- include "infinispan-helm-charts.labels" . | nindent 4 }}
  {{- if .Values.expose.annotations }}
  annotations:
    {{- range $annotationName, $annotationValue := .Values.expose.annotations }}
    {{ $annotationName | quote }}: {{ $annotationValue | quote }}
  {{- end }}
  {{- end }}
spec:
  {{- if .Values.expose.host }}
  host: {{ .Values.expose.host | quote }} }
  {{- end }}
  port:
    targetPort: 11222
  to:
    kind: Service
    name: {{ include "infinispan-helm-charts.name" . }}
  {{- else if .Capabilities.APIVersions.Has "networking.k8s.io/v1beta1/Ingress" }}
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: {{ include "infinispan-helm-charts.name" . }}
  labels:
    app: infinispan-ingress
  {{- include "infinispan-helm-charts.labels" . | nindent 4 }}
  {{- if .Values.expose.annotations }}
  annotations:
    {{- range $annotationName, $annotationValue := .Values.expose.annotations }}
    {{ $annotationName | quote }}: {{ $annotationValue | quote }}
  {{- end }}
  {{- end }}
spec:
  rules:
    {{- if .Values.expose.host }}
    - host: {{ .Values.expose.host | quote }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              serviceName: {{ include "infinispan-helm-charts.name" . }}
              servicePort: 11222
    {{- else }}
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              serviceName: {{ include "infinispan-helm-charts.name" . }}
              servicePort: 11222
  {{- end }}
  {{- end }}
  {{- end }}
